name: "3. Deploy dev to test"
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.PANTHEON_SSH_KEY }}
        config: ${{ secrets.SSH_CONFIG }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    - name: Installing Terminus
      uses: kopepasah/setup-pantheon-terminus@master
      with:
        pantheon-machine-token: ${{ secrets.PANTHEON_MACHINE_TOKEN }}
    - name: deployer
      env:
        pantheon_repo: '${{ secrets.PANTHEON_REPO }}'
        pantheon_site_name: '${{ secrets.PANTHEON_SITE_NAME }}'
      run: |
        echo Running terminus env:deploy teachforamerica.test  --yes
        terminus env:deploy teachforamerica.test  --yes
        echo Deployed code from dev to test environment
        
        echo Running terminus drush teachforamerica.test -- updb -y
        terminus drush teachforamerica.test -- updb -y
        
        echo Running terminus drush teachforamerica.test -- cim -y
        terminus drush teachforamerica.test -- cim -y
        
        echo Running terminus drush teachforamerica.test -- cr
        terminus drush teachforamerica.test -- cr

