name: "4. Deploy test to live"
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.PANTHEON_SSH_KEY }}
        config: ${{ secrets.SSH_CONFIG }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    - name: Installing Terminus
      uses: kopepasah/setup-pantheon-terminus@master
      with:
        pantheon-machine-token: ${{ secrets.PANTHEON_MACHINE_TOKEN }}
    - name: Deploy Code To Live
      run: |
        echo Creating backup of live environment for 365 days.
        terminus backup:create teachforamerica.live --keep-for=365 --no-interaction --yes
        echo Backup created.

        echo running terminus env:deploy teachforamerica.live --yes
        terminus env:deploy teachforamerica.live --yes
        echo Deployed code from test to live environment.

        echo running terminus drush teachforamerica.live -- updb -y
        terminus drush teachforamerica.live -- updb -y
        echo Ran Drush updb on live.

        echo running terminus drush teachforamerica.live -- cim -y
        terminus drush teachforamerica.live -- cim -y
        echo Ran Drush cim on live.

        echo running drush teachforamerica.live -- cr
        terminus drush teachforamerica.live -- cr
        echo Ran Drush cr on live.

        echo running terminus env:clear-cache teachforamerica.live
        terminus env:clear-cache teachforamerica.live
        echo Cleared Environment Cache.

        echo running drush teachforamerica.live -- watchdog:delete all -y
        terminus drush teachforamerica.live -- watchdog:delete all -y
        echo Cleared Log

        echo Deployment to live is complete.
    
    - name: Clear Akamai Caches on Live
      uses: jdmevo123/akamai-purge-action@1.7
      env:
        EDGERC: ${{ secrets.EDGERC }}
      with:
        command: 'invalidate' 
        type: 'url'
        ref: 'https://www.teachforamerica.org/ http://www.teachforamerica.org/ http://www.teachforamerica.org https://www.teachforamerica.org https://www.teachforamerica.org/sites/default/files/* http://www.teachforamerica.org/sites/default/files/* https://www.teachforamerica.org/themes/custom/polaris/dist/* https://www.teachforamerica.org/themes/custom/polaris/dist/css/* https://www.teachforamerica.org/themes/custom/polaris/dist/js/* http://www.teachforamerica.org/themes/custom/polaris/dist/css/* http://www.teachforamerica.org/themes/custom/polaris/dist/js/*'
        network: 'production'

    - name: Deploy Live Database To Dev
      run: |
        echo running terminus env:clone-content teachforamerica.live dev -y
        terminus env:clone-content teachforamerica.live dev -y
        echo Cloned database and files from teachforamerica.live environment to dev.
        
        echo running drush teachforamerica.dev -- updb -y
        terminus drush teachforamerica.dev -- updb -y

        echo running terminus drush teachforamerica.dev -- cim -y
        terminus drush teachforamerica.dev -- cim -y

        echo running drush teachforamerica.dev -- cr
        terminus drush teachforamerica.dev -- cr

        echo running terminus drush teachforamerica.dev -- sync-tfact-id -y
        terminus drush teachforamerica.dev -- sync-tfact-id -y
        echo Ran Drush sync-tfact-id on dev.

        echo Completed Synchronizing database and files to dev.
        
    - name: Clear Akamai Caches on Dev
      uses: jdmevo123/akamai-purge-action@1.7
      env:
        EDGERC: ${{ secrets.EDGERC }}
      with:
        command: 'invalidate' 
        type: 'url'
        ref: 'https://qamerlin.teachforamerica.org/ http://qamerlin.teachforamerica.org/ http://qamerlin.teachforamerica.org https://qamerlin.teachforamerica.org https://qamerlin.teachforamerica.org/sites/default/files/* http://qamerlin.teachforamerica.org/sites/default/files/* https://qamerlin.teachforamerica.org/themes/custom/polaris/dist/* https://qamerlin.teachforamerica.org/themes/custom/polaris/dist/css/* https://qamerlin.teachforamerica.org/themes/custom/polaris/dist/js/* http://qamerlin.teachforamerica.org/themes/custom/polaris/dist/css/* http://qamerlin.teachforamerica.org/themes/custom/polaris/dist/js/*'
        network: 'production'

    - name: Success
      run: |
        echo Completed Deployment to live and Database refresh to dev.
  
