name: Multidev on comment completed
on:
  workflow_run:
    workflows: [1. sPolaris To Multidev]
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Set latest commit status as ${{ job.status }}
        uses: myrotvorets/set-commit-status-action@master
        if: always()
        with:
          sha: ${{ COMMIT_NUMBER }}
          token: ${{ secrets.PANTHEON_MACHINE_TOKEN }}
          status: ${{ job.status }}

      - name: Add comment to PR
        uses: actions/github-script@v6
        if: always()
        with:
          script: |
            const name = '${{ github.workflow }}';
            const success = '${{ job.status }}' === 'success';
            const body = `${name}: ${success ? 'succeeded ✅' : 'failed ❌'}\n$`;
            
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            })