name: Create/Edit Multidev on comment
on:
  issue_comment:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/multidev')
    steps:

      - name: Get PR branch
        uses: xt0rted/pull-request-comment-branch@v2
        id: comment-branch

      - name: Set latest commit status as pending
        uses: myrotvorets/set-commit-status-action@master
        env:
          JOB_STATUS: ${{ job.status }}
          COMMIT_NUMBER: ${{ steps.comment-branch.outputs.head_sha }}
        with:
          sha: $COMMIT_NUMBER
          token: ${{ secrets.PANTHEON_MACHINE_TOKEN }}
          status: pending

      - name: Checkout PR branch ${{ steps.comment-branch.outputs.head_ref }}
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}

      - run: git rev-parse --abbrev-ref HEAD
      - run: git rev-parse --verify HEAD

      - name: Trigger workflow action
        uses: rshop/trigger-workflow-action@v1
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: DarkteK/DarkteK
          workflowId: 'polaris_branch_to_multidev.yml'
          branch: ${{ steps.comment-branch.outputs.head_ref }}
